### ISSUE TITLE
Build Failures with Spring Boot 2.3.0

### ISSUE THREAD

**Issue by bpack** [jaapcoomans/spring-boot-modules#2]
This project is a very helpful resource. I've attempted to adapt it using the latest versions of gradle and Spring Boot, but ran into a number of issues. So I tried using your project with Spring Boot 2.3.0 and ended up encountering test failures and a missing module issues in the security subproject - `module not found: tomcat.embed.core`. 

Wasn't sure if you had any intention to update to a more recent version of Spring Boot, but if not, feel free to close the issue. Thanks.

**Comment by jaapcoomans** [comment]
Hi @bpack , thanks for the kind words and also thanks for reporting this issue. I will definitely look into it as I notice more people are finding this project a useful reference. Also I still plan to give the talk associated with this project in other places, so for that reason too I want to update it. I currently don't have a lot of time for it, so it may take a while though.

**Comment by jaapcoomans** [comment]
I upgraded the application to Spring Boot 2.3.1 and upgraded all dependencies to recent versions. After that I replayed all the steps to make it modular. There were quite some notable changes because of that:
- Tomcat embedded now specifies an automatic module name (`org.apache.tomcat.embed.core`)
- Spring migrated to Jakarta EE dependencies, causing some interesting new conflicts. This led me to change the JAX-B implementation. Also there's some nasty duplicate module naming with Jakarta activation that required some workarounds.
- JUnit 5 is now in the `spring-boot-starter-test`, so there is no more need to explicitly depend on it.
- jjwt no longer has split package issues
- By far the most complex issue I bumped into was HikariCP. HikariCP 3.4.5 is a multi-release jar, which contains a module descriptor for Java 11 (and up). Unfortunately this module descriptor refers to the module `slf4j.api`, which is the filename-derived automatic module name of older versions of `slf4j-api`. Spring Boot 2.3 however brings in a newer version of slf4j, which declares automatic module name `org.slf4j` in its manifest. This leads to failure to load this module, which in turn leads to Spring autoconfiguration for Hikari not loading, causing a chain reaction which leads to the `EntityManager` not being initialized. Had to revert to the latest version that doesn't contain the offending module descriptor (3.4.3).
